# Generated by Django 5.0.2 on 2024-02-28 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutorRural',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_de_registro', models.CharField(max_length=100, unique=True, verbose_name='CPF ou CNPJ')),
                ('nome_produtor', models.CharField(max_length=100, verbose_name='Nome do produtor')),
                ('nome_fazenda', models.CharField(max_length=100, verbose_name='Nome da Fazenda')),
                ('cidade', models.CharField(max_length=50, verbose_name='Cidade')),
                ('estado', models.CharField(max_length=50, verbose_name='Estado')),
                ('area_total', models.FloatField(verbose_name='Área total em hectares da fazenda')),
                ('area_agricultavel', models.FloatField(verbose_name='Área agricultável em hectares')),
                ('area_vegetacao', models.FloatField(verbose_name='Área de vegetação em hectares')),
                ('cultura_plantada', models.CharField(max_length=50, verbose_name='Culturas plantadas')),
            ],
            options={
                'db_table': 'produtor_rural',
            },
        ),
    ]
