# Generated by Django 5.0.2 on 2024-02-28 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtor_rural', '0002_remove_produtorrural_cultura_plantada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtorrural',
            name='estado',
            field=models.CharField(choices=[('ac', 'Acre'), ('al', 'Alagoas'), ('ap', 'Amapá'), ('am', 'Amazonas'), ('ba', 'Bahia'), ('ce', 'Ceará'), ('df', 'Distrito Federal'), ('es', 'Espírito Santo'), ('go', 'Goiás'), ('ma', 'Maranhão'), ('mt', 'Mato Grosso'), ('ms', 'Mato Grosso do Sul'), ('mg', 'Minas Gerais'), ('pa', 'Pará'), ('pb', 'Paraíba'), ('pr', 'Paraná'), ('pe', 'Pernambuco'), ('pi', 'Piauí'), ('rj', 'Rio de Janeiro'), ('rn', 'Rio Grande do Norte'), ('rs', 'Rio Grande do Sul'), ('ro', 'Rondônia'), ('rr', 'Roraima'), ('sc', 'Santa Catarina'), ('sp', 'São Paulo'), ('se', 'Sergipe'), ('to', 'Tocantins')], max_length=50, verbose_name='Estado'),
        ),
        migrations.CreateModel(
            name='CulturaPlantada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cultura', models.CharField(choices=[('soja', 'Soja'), ('milho', 'Milho'), ('algodao', 'Algodão'), ('cafe', 'Café'), ('cana_de_acucar', 'Cana de Açucar')], max_length=50, verbose_name='Cultura plantada')),
                ('produtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cultura_plantada', to='produtor_rural.produtorrural')),
            ],
            options={
                'verbose_name': 'Cultura',
                'db_table': 'cultura_plantada',
            },
        ),
    ]
