# Generated by Django 5.0.2 on 2024-02-29 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtor_rural', '0004_alter_culturaplantada_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtorrural',
            name='area_agricultavel',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Área agricultável em hectares'),
        ),
        migrations.AlterField(
            model_name='produtorrural',
            name='area_total',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Área total em hectares da fazenda'),
        ),
        migrations.AlterField(
            model_name='produtorrural',
            name='area_vegetacao',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Área de vegetação em hectares'),
        ),
    ]
