# Generated by Django 5.0.2 on 2024-03-01 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtor_rural', '0005_alter_produtorrural_area_agricultavel_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='culturaplantada',
            options={'verbose_name': 'Culturas Plantada'},
        ),
    ]
